# Generated by Django 5.2.10 on 2026-01-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NcmMva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncm', models.CharField(db_index=True, max_length=8)),
                ('descricao', models.TextField()),
                ('mva', models.DecimalField(decimal_places=2, max_digits=6)),
                ('portaria', models.CharField(max_length=50)),
                ('inicio_vigencia', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ncm'],
                'unique_together': {('ncm', 'portaria')},
            },
        ),
    ]
