# Generated by Django 5.2.10 on 2026-01-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_ncmmva'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ncm',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
